// @vitest-environment node
/**
 * Tailwind 4 source coverage (replaces tailwind-content.test.ts, plan 04-01).
 *
 * Tailwind 3 generated only the classes found in the `content` globs of tailwind.config.js. Tailwind 4
 * with `@import 'tailwindcss' source(none)` does the same through explicit `@source` lines in
 * src/app/globals.css, so a directory that sets a className but is missing there silently loses its
 * classes (the map legend lost bottom-4/right-4 that way, found in the 03-15 review captures).
 *
 * The test fails when: the entry stops using source(none), a covered directory loses its @source line,
 * a file that sets a className lives outside the covered directories, a class used only under
 * src/features is not generated by a real compile, the legacy `.glass-panel` ends up inside a cascade
 * layer (it must stay unlayered so it keeps beating utilities as it did under Tailwind 3), or a Tailwind 3
 * config or PostCSS plugin comes back.
 */
import { describe, expect, it } from 'vitest';
import fs from 'node:fs';
import path from 'node:path';
import postcss from 'postcss';
import tailwindcss from '@tailwindcss/postcss';

const ROOT = path.resolve(__dirname, '../..');
const SRC = path.join(ROOT, 'src');
const GLOBALS = path.join(SRC, 'app/globals.css');

const COVERED = ['src/pages', 'src/components', 'src/app', 'src/features'];

function read(file: string): string {
  return fs.readFileSync(file, 'utf-8').replace(/\r\n/g, '\n');
}

function walk(dir: string, out: string[] = []): string[] {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) walk(full, out);
    else if (/\.(ts|tsx|js|jsx|mdx)$/.test(entry.name)) out.push(full);
  }
  return out;
}

function sourceDirs(css: string): string[] {
  // `@source "../features";` is relative to src/app/globals.css.
  return [...css.matchAll(/^@source\s+"([^"]+)";/gm)].map((m) =>
    path.relative(ROOT, path.resolve(path.dirname(GLOBALS), m[1])).split(path.sep).join('/')
  );
}

describe('tailwind 4 sources', () => {
  const css = read(GLOBALS);

  it("starts with @import 'tailwindcss' source(none); and declares @source for the four directories", () => {
    expect(css.startsWith("@import 'tailwindcss' source(none);")).toBe(true);
    expect(sourceDirs(css).sort()).toEqual([...COVERED].sort());
  });

  it('covers every source directory that sets a className', () => {
    const uncovered = walk(SRC)
      .filter((file) => /className\s*=/.test(read(file)))
      .map((file) => path.relative(ROOT, file).split(path.sep).join('/'))
      .filter((rel) => !COVERED.some((p) => rel === p || rel.startsWith(`${p}/`)));
    expect(uncovered, 'files whose classes Tailwind would never generate').toEqual([]);
  });

  it('generates a class used only under src/features, and keeps .glass-panel unlayered', async () => {
    const result = await postcss([tailwindcss()]).process(css, { from: GLOBALS });

    // w-[calc(100%-2rem)] appears only in src/features/contract/ContractVersionSync.tsx (no other file
    // under src sets it), so it is generated only if the @source "../features" line works.
    expect(result.css).toContain(String.raw`.w-\[calc\(100\%-2rem\)\]`);

    let glassPanelRules = 0;
    result.root.walkRules((rule) => {
      if (!rule.selectors.some((s) => s === '.glass-panel')) return;
      glassPanelRules += 1;
      for (let parent = rule.parent; parent && parent.type !== 'root'; parent = parent.parent) {
        if (parent.type === 'atrule' && (parent as postcss.AtRule).name === 'layer') {
          throw new Error('.glass-panel must stay outside any @layer block');
        }
      }
    });
    expect(glassPanelRules).toBeGreaterThan(0);
  });

  it('keeps the Tailwind 3 hover selector outside the instrument surface and the media gate inside it', async () => {
    const result = await postcss([tailwindcss()]).process(css, { from: GLOBALS });
    // hover:text-bone is a legacy utility (src/app/page.tsx); hover:underline is used by the kit too.
    const SURFACE = "[data-surface='instrument']";
    let legacyUngated = 0;
    let surfaceGated = 0;
    result.root.walkRules((rule) => {
      if (!rule.selector.startsWith(String.raw`.hover\:text-bone`)) return;
      const gated = (() => {
        for (let parent = rule.parent; parent && parent.type !== 'root'; parent = parent.parent) {
          if (parent.type === 'atrule' && (parent as postcss.AtRule).name === 'media') {
            return (parent as postcss.AtRule).params.replace(/\s+/g, '') === '(hover:hover)';
          }
        }
        return false;
      })();
      if (rule.selector.includes(`:not(${SURFACE} *)`)) {
        expect(gated, 'legacy hover must fire on touch, as under Tailwind 3').toBe(false);
        legacyUngated += 1;
      } else if (rule.selector.includes(`:where(${SURFACE} *)`)) {
        expect(gated, 'inside the instrument surface hover stays media-gated').toBe(true);
        surfaceGated += 1;
      }
    });
    expect(legacyUngated).toBeGreaterThan(0);
    expect(surfaceGated).toBeGreaterThan(0);
  });

  it('has no Tailwind 3 config and one PostCSS plugin, @tailwindcss/postcss', () => {
    expect(fs.existsSync(path.join(ROOT, 'tailwind.config.js'))).toBe(false);
    expect(fs.existsSync(path.join(ROOT, 'tailwind.config.ts'))).toBe(false);
    const config = require(path.join(ROOT, 'postcss.config.js')) as { plugins: Record<string, unknown> };
    expect(Object.keys(config.plugins)).toEqual(['@tailwindcss/postcss']);
  });
});
