#!/usr/bin/env python3
"""
Merge expansion embeddings into metadata_v6.json.

Reads expansion_embeddings.json (generated by generate_expansion_embeddings.py)
and patches matching sites in metadata_v6.json with their real embeddings.

Usage:
    python3 scripts/merge_expansion_embeddings.py
"""

import json
from pathlib import Path
import time

EXPANSION_PATH = Path('data/embeddings/expansion_embeddings.json')
METADATA_PATH = Path('data/embeddings/metadata_v6.json')


def main():
    # Load expansion embeddings
    if not EXPANSION_PATH.exists():
        print(f"ERROR: {EXPANSION_PATH} not found. Run generate_expansion_embeddings.py first.")
        return

    with open(EXPANSION_PATH) as f:
        expansion = json.load(f)

    if not expansion:
        print("ERROR: No embeddings found in expansion_embeddings.json")
        return

    print(f"Expansion embeddings: {len(expansion)} sites")
    for site_id, emb in expansion.items():
        print(f"  {site_id}: {len(emb)} dims")

    # Load metadata v6
    with open(METADATA_PATH) as f:
        metadata = json.load(f)

    print(f"\nMetadata v6: {metadata['total_sites']} sites")

    # Patch embeddings
    updated = 0
    for site in metadata['sites']:
        sid = site['site_id']
        if sid in expansion:
            site['embedding'] = expansion[sid]
            site['has_embedding'] = True
            updated += 1
            print(f"  Patched: {sid} ({len(expansion[sid])} dims)")

    if updated == 0:
        print("\nWARNING: No sites were updated. Check site_id matching.")
        print(f"  Expansion keys: {list(expansion.keys())}")
        print(f"  Metadata new site IDs: {[s['site_id'] for s in metadata['sites'] if s.get('country') in ('USA', 'French Polynesia')]}")
        return

    # Update metadata
    metadata['generated_at'] = time.strftime('%Y-%m-%dT%H:%M:%SZ')

    # Count stats
    with_emb = sum(1 for s in metadata['sites'] if s.get('has_embedding') and len(s.get('embedding', [])) > 0)
    without_emb = len(metadata['sites']) - with_emb

    print(f"\n=== Summary ===")
    print(f"Total sites: {len(metadata['sites'])}")
    print(f"With embeddings: {with_emb}")
    print(f"Location-only: {without_emb}")
    print(f"Just updated: {updated}")

    # Save
    with open(METADATA_PATH, 'w') as f:
        json.dump(metadata, f)

    print(f"\nSaved to {METADATA_PATH}")
    print(f"\nNext: re-upload to S3:")
    print(f"  python3 scripts/upload_metadata_v6.py")


if __name__ == '__main__':
    main()
